### ISSUE TITLE
Removes NewLines on tag lines

### ISSUE THREAD

**Issue by aloisdeniel** [jehugaleahsa/mustache-sharp#42]
For me a simple approach would be to remove new lines for lines thats contain only tags when not using `{{#NewLine}}` tag

For example, here is a template :

```
{{#each Items}}
{{#if IsOk}}
That's okay !
{{#else}}
Nope ...
{{/if}}
{{/each}}
```

Currently, the ouput would be for example

```


That's okay !

That's okay !

Nope...

```

It could be great if we could have the lines with only tag ignored 

```
That's okay !
That's okay !
Nope...
```

**Comment by natemcmaster** [comment]
:+1:
