### ISSUE TITLE
Different syntax of "else"

### ISSUE THREAD

**Issue by joseph1125** [jehugaleahsa/mustache-sharp#47]
In handlebars.js, else is implemented as "{{else}}" while in mustache-sharp is implemented as "{{#else}}", any workaround of this issue?

Moreover, in the meanwhile, I'm trying to fix this problem by using "#unless" and found that it is not supported, any possible workaround?

**Comment by nickytonline** [comment]
@joseph1125, I've implemented the unless tag as well as support for the handlebars.js if/else syntax in [mosharp](https://github.com/nickytonline/mosharp).

Later, Nick
