### ISSUE TITLE
Windows service

### ISSUE THREAD

**Issue by oscaruribe** [jehugaleahsa/mustache-sharp#49]
We've experienced failures when running the package in a windows service. Works great in console mode but fails in parallel.for.

**Comment by jehugaleahsa** [comment]
Can you give me the particulars of the version/changeset you're using?
I know I fixed some threading issues in the past.

Maybe you could include a stack trace from your logs. You have to give me a starting point!

**Comment by oscaruribe** [comment]
It doesn't appear to fail anymore:) Probably some other error.
