### ISSUE TITLE
Mustache-sharp does not have a strong name

### ISSUE THREAD

**Issue by PI2R** [jehugaleahsa/mustache-sharp#55]
Hi,

From Visual Studio 2013, I could not find a signed version of Mustache-sharp using the NugetPackage management.

Does it exist or should I create it myself from the sources? (which I'd rather not do in order to be able to keep the package management aspect of the thing :-))

Thanks in advance for your help

Cheers
Pierre

**Comment by jehugaleahsa** [comment]
Done. Let me know if you have any problems.

**Comment by PI2R** [comment]
Perfect!
Thanks a lot :-)
