### ISSUE TITLE
Is there a way to suppress KeyNotFoundException?

### ISSUE THREAD

**Issue by oscaruribe** [jehugaleahsa/mustache-sharp#58]
If you're trying to render a text and the data doesn't include a key it fails, I'd rather it just replaced with blank. Is there any way to do that with a flag?

**Comment by jehugaleahsa** [comment]
You can add an event handler to the generator and set the Handled property
to true.
https://github.com/jehugaleahsa/mustache-sharp/blob/master/mustache-sharp/KeyNotFoundEventArgs.cs

**Comment by oscaruribe** [comment]
Awesome! Worked like a charm. Thanks Travis!


Best regards

Oscar Uribe
Founder / Chief Executive Officer
oscar.uribe@ungapped.com<mailto:oscar.uribe@ungapped.com> | SE: +46 733 526 000, US: +1 (415) 505 68 63
www.linkedin.com/in/oscaruribe<http://www.linkedin.com/in/oscaruribe>

[Ungapped]<http://www.ungapped.com/>
Ungapped | ungapped.com<https://ungapped.com/>
Rådmansgatan 65, 113 60 Stockholm Sweden | +46 (0)8 410 413 13
180 Sansome St, San Francisco, CA 94104 | +1 (800) 931-6339

Follow: Facebook<https://www.facebook.com/ungapped> | Twitter<https://twitter.com/ungapped> | LinkedIn<https://www.linkedin.com/company/ungapped> | Pinterest<https://www.pinterest.com/ungapped/>

Från: Travis Parks [mailto:notifications@github.com]
Skickat: den 11 februari 2016 14:03
Till: jehugaleahsa/mustache-sharp <mustache-sharp@noreply.github.com>
Kopia: Oscar Uribe Enggren <oscar.uribe@ungapped.com>
Ämne: Re: [mustache-sharp] Is there a way to suppress KeyNotFoundException? (#58)

You can add an event handler to the generator and set the Handled property
to true.
https://github.com/jehugaleahsa/mustache-sharp/blob/master/mustache-sharp/KeyNotFoundEventArgs.cs
