### ISSUE TITLE
Portable library (legacy or netstandard) and dotnet core support

### ISSUE THREAD

**Issue by sandorfr** [jehugaleahsa/mustache-sharp#62]
Hello,

I've been maintaining a fork providing a portable and .net core support (formerly kre, vnext, dnx, etc...). Now .net core as reached some stability, it might be interesting to reintegrate this into your repo. 

Diff
https://github.com/jehugaleahsa/mustache-sharp/compare/master...sandorfr:rc2?diff=unified&name=rc2

If you are interested I'll squash the commits and make a PR.

Thanks for this lib btw.

**Comment by sandorfr** [comment]
@jehugaleahsa any thoughts?

**Comment by snboisen** [comment]
I guess this project is dead...

**Comment by sandorfr** [comment]
I don't know, but I'm still maintaining and using  my fork which is published here https://www.nuget.org/packages/mustache-netstandard/
