### ISSUE TITLE
Feature Request: Include support for method calls

### ISSUE THREAD

**Issue by ryno1234** [jehugaleahsa/mustache-sharp#67]
I find myself needing this when referencing a Date object. I'd love to be able to get the result of ToShortDateString(). In order to use this for my intended purpose, I need to create a whole new custom object to represent all my values in the template, as opposed to using the objects I already have available.

Thoughts?

**Comment by jehugaleahsa** [comment]
Placeholders accept format flags, the same as String.Format. I think
ToShortDateString() is the same as the "d" standard format, eg,
ToString("d") or {key:d} in mustache #.

**Comment by ryno1234** [comment]
I overlooked this. Perfect, thank you!
