### ISSUE TITLE
{{ }} around property with spaces in the name

### ISSUE THREAD

**Issue by srg-avai** [jehugaleahsa/mustache-sharp#82]
Hi - are spaces in the property names possible / is there some way to specify a literal key reference?

ie 
```
modelDictionary = [
'Prop with Spaces':{
value: 'some string';
}
] //oversimplification of c# dictionary

...

var compiler = new FormatCompiler();
var generator = compiler.Compile(@"{{Prop with Spaces}}");
var name = generator.Render(modelDictionary);
//where name is now 'some string'
```

In the above example, mustache# doesnt find the key in the render step and value of name ends up being {{Prop with Spaces}}

In the readme overview of mustache-sharp handlebarsjs is mentioned... its not clear to me how literal this is to be taken but heres how its handled in handlebarsjs (doesnt work w/ mustache-sharp): https://github.com/wycats/handlebars.js/issues/358

**Comment by jehugaleahsa** [comment]
One restriction mustache# has always had is that property names must be valid C# property names. This is primarily because it does not discern between dictionaries and objects when looking up values, so it couldn't know if spaces *should be* valid in one case but not the other.

**Comment by srg-avai** [comment]
@jehugaleahsa thank you for your quick response
