### ISSUE TITLE
adding padding spaces to an identifier

### ISSUE THREAD

**Issue by last-Programmer** [jehugaleahsa/mustache-sharp#83]
Hi,
I would like to make the identifier specific width by adding right side spaces?

How to do that?

Thanks

**Comment by jehugaleahsa** [comment]
The placeholders use the same formatting that `String.Format` accepts: https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.2#controlling-spacing

**Comment by last-Programmer** [comment]
can you please give me an example? because it does not work

I tried this {{Name:{0,40}}} . It does not work. I get the error input string was not in correct format

**Comment by last-Programmer** [comment]
sorry i got it by doing {{Name,40}}..Thanks
